.PHONY: all clean
CC=g++ -O2
all: exewithident smoketest
	@if ! strings smoketest | grep 'id:';then true; \
	else \
		echo 'Smoke test failed. -O2 doesnt remove unused static const char*';\
		false;\
	fi
	@echo "Strings in executable generated by Ident"
	strings exewithident | grep 'id:'

smoketest: smoketest.cc
	$(CC) $^ -o $@

exewithident: ident.o a.o b.o g.o main.o
	$(CC) $^ -o $@

%.o: %.cc
	$(CC) -c $< -o $@

clean:
	rm *.o smoketest exewithident
